## セットアップ

```{r}
#| label: setup
library(tools)
library(Momocs)
source("scripts/functions.R")
palette("Okabe-Ito")
```

## 輪郭データの読み込み

```{r}
#| label: species_name
df_sp_name <- read.csv("data/species_name.csv")
df_sp_name$species <- ifelse(
  df_sp_name$konara < df_sp_name$mizunara,
  "mizunara",
  "konara"
)
```

```{r}
#| label: load_contours
file_paths_xy <- list.files(
  "data/contour/",
  full.names = TRUE,
  pattern = "\\.csv$"
)
id_name <- file_path_sans_ext(basename(file_paths_xy))

id_name_head <- lapply(id_name, function(x) {
  parts <- unlist(strsplit(x, "_"))
  return(parts[1])
})
id_name_head <- unlist(id_name_head)
# 種名の対応付け
sp_name <- df_sp_name$species[match(id_name_head, df_sp_name$id)]

xy_list <- lapply(file_paths_xy, function(fp) {
  cat("File:", fp, "\n")
  df <- read.csv(fp)
  df <- df[, c("x", "y")]
  df <- as.matrix(df)
  storage.mode(df) <- "double"
  # 輪郭が閉じていない場合、最初の点を最後に追加して閉じる
  if (!all(df[1, ] == df[nrow(df), ])) {
    df <- rbind(df, df[1, ])
  }
  return(df)
})
names(xy_list) <- id_name
```

## データの読み込み

```{r} 
file_paths <- list.files(
  "data/coefficients_efd_normalized",
  full.names = TRUE,
  pattern = "\\.csv$"
)
ef_list <- lapply(file_paths, function(fp) {
  cat("File:", fp, "\n")
  df <- read.csv(fp)
  return(df)
})
```

## 関数の作成

```{r}
compare_contour_oriented_ture_EFD_normalization <- function(
  original,
  ef_normalized,
  label = NULL,
  nb.h = 35,
  mar = c(0, 0, 0, 0),
  cex.text = 2,
  ...
) {
  #original <- xy_list[[i]]
  center <- coo_centpos(original) # center position
  original_centered <- sweep(original, 2, center, "-") # center the contour
  ef <- efourier(
    original_centered,
    nb.h = nb.h,
    norm = FALSE
  )
  true_ef <- true_normalize(ef, output_meta = TRUE)
  scale <- true_ef$E
  #ef_normalized <- ef_list[[i]]
  true_ef_coef <- list(
    ao = unique(ef_normalized$ao),
    co = unique(ef_normalized$co),
    an = ef_normalized$an,
    bn = ef_normalized$bn,
    cn = ef_normalized$cn,
    dn = ef_normalized$dn
  )
  # reonstruct contour from true EFD coefficients
  reconstruct <- efourier_i(true_ef_coef, nb.h = nb.h)
  df_reconstruct <- as.data.frame(reconstruct)
  df_reconstruct <- df_reconstruct * scale
  xlim <- range(c(df_reconstruct$x, original_centered[, 1]))
  par(mar = mar)
  # original centered contour
  plot(
    original_centered,
    type = "l",
    asp = 1,
    col = adjustcolor("black", red = 0.7, green = 0.7, blue = 0.7),
    xlim = xlim,
    bty = "n",
    xaxt = "n",
    yaxt = "n",
    xlab = "",
    ylab = "",
    ...
  )

  # reconstructed contour
  lines(
    df_reconstruct,
    type = "l",
    asp = 1,
    col = adjustcolor("#FF4B00", alpha.f = 0.9),
    ...
  )

  # label
  if (!is.null(label)) {
    text(
      x = mean(par("usr")[1:2]),
      y = mean(par("usr")[3:4]),
      labels = label,
      cex = cex.text,
      col = "black"
    )
  }
}

compare_contour_oriented_ture_EFD_normalization(
  original = xy_list[[1]],
  ef_normalized = ef_list[[1]],
  label = names(xy_list)[1],
  nb.h = 35,
  mar = c(0, 0, 0, 0),
  lwd = 2,
  cex.text = 1
)
```

## すべての輪郭と再構築輪郭を保存

```{r}
save_dir <- "results/contours_reconstruction/"
dir.create(save_dir, recursive = TRUE, showWarnings = FALSE)
list_id <- list(
  1:50,
  51:100,
  101:150,
  151:200,
  201:250,
  251:300,
  301:350,
  351:400,
  401:450,
  451:500,
  501:550,
  551:600,
  601:650,
  651:700,
  701:746
)

for (ids in list_id) {
  ids <- unlist(ids)
  save_path <- paste0(
    save_dir,
    "reconstructed_contours_",
    min(ids),
    "_",
    max(ids),
    ".svg"
  )
  svg(save_path, width = 10, height = 5, bg = "transparent")
  layout(matrix(1:50, nrow = 5, byrow = TRUE))
  for (id in ids) {
    compare_contour_oriented_ture_EFD_normalization(
      original = xy_list[[id]],
      ef_normalized = ef_list[[id]],
      label = names(xy_list)[id],
      nb.h = 35,
      mar = c(0, 0, 0, 0),
      lwd = 2,
      cex.text = 1
    )
  }
  dev.off()
}
```

## 一部のIDの取り出し

```{r}
idx_left <- c(1:5, 181:184)
idx_right <- c(322, 374, 375, 376, 378, 595, 596, 746, 372)
labels_left <- letters[1:9]
labels_right <- letters[10:18]

save_filename <- "results/contours_reconstruction/leftward_examples.svg"
svg(save_filename, bg = "transparent")
layout(matrix(1:9, nrow = 3, byrow = TRUE))
for (i in seq_along(idx_left)) {
  compare_contour_oriented_ture_EFD_normalization(
    original = xy_list[[idx_left[i]]],
    ef_normalized = ef_list[[idx_left[i]]],
    label = labels_left[i],
    nb.h = 35,
    mar = c(0, 0, 0, 0),
    lwd = 3,
    cex.text = 3
  )
}
dev.off()

# right side
save_filename <- "results/contours_reconstruction/rightward_examples.svg"
svg(save_filename, bg = "transparent")
layout(matrix(1:9, nrow = 3, byrow = TRUE))
for (i in seq_along(labels_right)) {
  compare_contour_oriented_ture_EFD_normalization(
    original = xy_list[[idx_right[i]]],
    ef_normalized = ef_list[[idx_right[i]]],
    label = labels_right[i],
    nb.h = 35,
    mar = c(0, 0, 0, 0),
    lwd = 3,
    cex.text = 3
  )
}
dev.off()
```
