
## セットアップ

```{r}
#| label: setup
library(tools)
library(Momocs)
source("scripts/functions.R")
palette("Okabe-Ito")
```

## 輪郭データの読み込み

```{r}
#| label: species_name
df_sp_name <- read.csv("data/species_name.csv")
df_sp_name$species <- ifelse(
  df_sp_name$konara < df_sp_name$mizunara,
  "mizunara",
  "konara"
)
```

```{r}
#| label: load_contours
file_paths_xy <- list.files(
  "data/contour/",
  full.names = TRUE,
  pattern = "\\.csv$"
)
id_name <- file_path_sans_ext(basename(file_paths_xy))

id_name_head <- lapply(id_name, function(x) {
  parts <- unlist(strsplit(x, "_"))
  return(parts[1])
})
id_name_head <- unlist(id_name_head)
# 種名の対応付け
sp_name <- df_sp_name$species[match(id_name_head, df_sp_name$id)]

xy_list <- lapply(file_paths_xy, function(fp) {
  cat("File:", fp, "\n")
  df <- read.csv(fp)
  df <- df[, c("x", "y")]
  df <- as.matrix(df)
  storage.mode(df) <- "double"
  # 輪郭が閉じていない場合、最初の点を最後に追加して閉じる
  if (!all(df[1, ] == df[nrow(df), ])) {
    df <- rbind(df, df[1, ])
  }
  return(df)
})
names(xy_list) <- id_name

out <- Out(xy_list, fac = data.frame(species = factor(sp_name))) # MomocsのOutオブジェクトに変換
names(out) <- id_name
```


## True EFD normalization後の輪郭の再構築

```{r}
file_paths_true_efd <- list.files(
  "data/coefficients_efd_normalized/",
  full.names = TRUE,
  pattern = "\\.csv$"
)
id_name <- file_path_sans_ext(basename(file_paths_true_efd))

reconst_list <- lapply(file_paths_true_efd, function(fp) {
  cat("File:", fp, "\n")
  df <- read.csv(fp)
  reconstructed_shape <- efourier_shape(
    df$an,
    df$bn,
    df$cn,
    df$dn,
    nb.pts = 120,
    plot = FALSE
  )
  return(reconstructed_shape)
})
out_reconst <- Out(reconst_list, fac = data.frame(species = factor(sp_name))) # MomocsのOutオブジェクトに変換
names(out_reconst) <- id_name
```

## すべての輪郭と再構築輪郭のプロット

```{r}
save_dir <- "results/contours_reconstruction/"
dir.create(save_dir, recursive = TRUE, showWarnings = FALSE)
idx <- list(
  1:50,
  51:100,
  101:150,
  151:200,
  201:250,
  251:300,
  301:350,
  351:400,
  401:450,
  451:500,
  501:550,
  551:600,
  601:650,
  651:700,
  701:746
)

for (i in seq_along(idx)) {
  slice_i_original <- slice(out, idx[[i]])
  slice_i_reconst <- slice(out_reconst, idx[[i]])
  svg_filename <- paste0(
    save_dir,
    "reconstructed_contours_",
    min(idx[[i]]),
    "_",
    max(idx[[i]]),
    ".svg"
  )
  svg(svg_filename, width = 10, height = 5, bg = "transparent")
  panel(
    slice_i_original,
    dim = c(5, 10),
    names = TRUE,
    borders = adjustcolor(1, alpha.f = 0.9),
    lwd = 2
  )
  par(new = TRUE) # overlay
  panel(
    slice_i_reconst,
    dim = c(5, 10),
    names = TRUE,
    borders = adjustcolor(7, alpha.f = 0.9),
    lwd = 2
  )
  dev.off()
}
```

## 一部のIDの取り出し

本手法では、向きは統一されていますが、回転後の輪郭と再構築輪郭の向きが異なる場合があります。
それとの対応のため、一部を取り出します。

```{r}
idx_left <- c(1:5, 181:184)
idx_right <- c(322, 372, 374, 375, 376, 378, 595, 596, 746)
slice_original_left <- slice(out, idx_left)
slice_reconstructed_left <- slice(out_reconst, idx_left)
names(slice_original_left) <- letters[1:length(idx_left)]

slice_original_right <- slice(out, idx_right)
slice_reconstructed_right <- slice(out_reconst, idx_right)
names(slice_original_right) <- letters[
  (length(idx_left) + 1):(length(idx_left) + length(idx_right))
]

dims <- c(3, 3)
cex_names <- 1.5

# left side
save_filename <- "results/contours_reconstruction/leftward_examples.svg"
svg(save_filename, width = 10, height = 5, bg = "transparent")
panel(
  slice_original_left,
  dim = dims,
  borders = adjustcolor(1, alpha.f = 0.9),
  names = TRUE,
  cex.names = cex_names
)
par(new = TRUE) # overlay
panel(
  slice_reconstructed_left,
  dim = dims,
  borders = adjustcolor(7, alpha.f = 0.9)
)
dev.off()

# right side
save_filename <- "results/contours_reconstruction/rightward_examples.svg"
svg(save_filename, width = 10, height = 5, bg = "transparent")
panel(
  slice_original_right,
  dim = dims,
  borders = adjustcolor(1, alpha.f = 0.9),
  names = TRUE,
  cex.names = cex_names
)
par(new = TRUE) # overlay
panel(
  slice_reconstructed_right,
  dim = dims,
  borders = adjustcolor(7, alpha.f = 0.9)
)
dev.off()
```
