## セットアップ

```{r}
#| label: setup

library(tools)
library(Momocs)
source("scripts/functions.R")
palette("Okabe-Ito")
```

## 輪郭データの読み込み

```{r}
#| label: load_contours

file_paths_xy <- list.files(
  "data/contour_triadica_sebifera//",
  full.names = TRUE,
  pattern = "\\.csv$"
)
id_name <- file_path_sans_ext(basename(file_paths_xy))

xy_list <- lapply(file_paths_xy, function(fp) {
  cat("File:", fp, "\n")
  df <- read.csv(fp)
  df <- df[, c("x", "y")]
  df <- as.matrix(df)
  storage.mode(df) <- "double"
  # 輪郭が閉じていない場合、最初の点を最後に追加して閉じる
  if (!all(df[1, ] == df[nrow(df), ])) {
    df <- rbind(df, df[1, ])
  }
  return(df)
})
names(xy_list) <- id_name
```

```{r} 
file_paths <- list.files(
  "data/coefficients_efd_normalized_triadica_sebifera",
  full.names = TRUE,
  pattern = "\\.csv$"
)
ef_list <- lapply(file_paths, function(fp) {
  cat("File:", fp, "\n")
  df <- read.csv(fp)
  return(df)
})
```

## 関数の作成

```{r}
compare_contour_oriented_ture_EFD_normalization <- function(
  original,
  ef_normalized,
  label = NULL,
  nb.h = 35,
  mar = c(0, 0, 0, 0),
  cex.text = 2,
  ...
) {
  # スケール E* を計算する関数
  compute_E_star <- function(ef) {
    A1 <- ef$an[1]
    B1 <- ef$bn[1]
    C1 <- ef$cn[1]
    D1 <- ef$dn[1]
    # θ の計算（主軸の方向）
    theta <- 0.5 *
      atan2(
        2 * (A1 * B1 + C1 * D1),
        (A1^2 + C1^2 - B1^2 - D1^2)
      )

    # a*, c* の計算
    a_star <- A1 * cos(theta) + B1 * sin(theta)
    c_star <- C1 * cos(theta) + D1 * sin(theta)

    # E*（半長軸の長さ）
    E_star <- sqrt(a_star^2 + c_star^2)
    return(E_star)
  }

  #original <- xy_list[[i]]
  center <- coo_centpos(original) # center position
  original_centered <- sweep(original, 2, center, "-") # center the contour
  ef <- efourier(
    original_centered,
    nb.h = nb.h,
    norm = FALSE
  )
  E <- compute_E_star(ef)
  #true_ef <- true_normalize(ef, output_meta = TRUE)
  #scale <- true_ef$E
  true_ef_coef <- list(
    ao = unique(ef_normalized$ao),
    co = unique(ef_normalized$co),
    an = ef_normalized$an,
    bn = ef_normalized$bn,
    cn = ef_normalized$cn,
    dn = ef_normalized$dn
  )
  # reonstruct contour from true EFD coefficients
  reconstruct <- efourier_i(true_ef_coef, nb.h = nb.h)
  df_reconstruct <- as.data.frame(reconstruct)
  df_reconstruct <- df_reconstruct * E
  xlim <- range(c(df_reconstruct$x, original_centered[, 1]))
  ylim <- range(c(df_reconstruct$y, original_centered[, 2]))
  par(mar = mar)
  # original centered contour
  plot(
    original_centered,
    type = "l",
    asp = 1,
    col = adjustcolor("black", red = 0.7, green = 0.7, blue = 0.7),
    xlim = xlim,
    ylim = ylim,
    bty = "n",
    xaxt = "n",
    yaxt = "n",
    xlab = "",
    ylab = "",
    ...
  )

  # reconstructed contour
  lines(
    df_reconstruct,
    asp = 1,
    col = adjustcolor("#FF4B00", alpha.f = 0.9),
    ...
  )

  # label
  if (!is.null(label)) {
    text(
      x = mean(par("usr")[1:2]),
      y = mean(par("usr")[3:4]),
      labels = label,
      cex = cex.text,
      col = "black"
    )
  }
}
```

## すべての輪郭と再構築輪郭を保存

Oriented True EFD normalization からの再構築輪郭と元の輪郭を重ね合わせます。

```{r}
save_dir <- "results"
dir.create(save_dir, showWarnings = FALSE)
save_file_name <- "compare_contours_oriented_true_efd_normalized_triadica_sebifera.svg"
svg(file.path(save_dir, save_file_name), bg = "transparent")
layout(matrix(seq_along(xy_list), nrow = 5, byrow = TRUE))
for (i in seq_along(xy_list)) {
  compare_contour_oriented_ture_EFD_normalization(
    original = xy_list[[i]],
    ef_normalized = ef_list[[i]],
    label = names(xy_list)[i],
    nb.h = 5,
    mar = c(0, 0, 0, 0),
    lwd = 2,
    cex.text = 1
  )
}
dev.off()
```

## 一部を保存

```{r}
save_dir <- "results"
dir.create(save_dir, showWarnings = FALSE)
save_file_name <- "compare_contours_oriented_true_efd_normalized_triadica_sebifera_example.svg"
svg(file.path(save_dir, save_file_name), bg = "transparent")
xy_list_example <- xy_list[1:9]
labels <- letters[seq_along(xy_list_example)]
layout(matrix(seq_along(xy_list_example), nrow = 3, byrow = TRUE))
for (i in seq_along(xy_list_example)) {
  compare_contour_oriented_ture_EFD_normalization(
    original = xy_list[[i]],
    ef_normalized = ef_list[[i]],
    nb.h = 5,
    mar = c(0, 0, 0, 0),
    lwd = 3,
    cex.text = 5,
    label = labels[i]
  )
}
dev.off()
```

## 普通の True EFD normalization を行った場合

取得した輪郭から、回転して、通常の True EFD normalization を行い、輪郭を再構築して確認します。
長軸を x 軸に揃えるように回転させるため、サンプル間で向きがそろわない可能性があります。

### 関数の作成

```{r}
compare_contour <- function(
  original,
  label = NULL,
  nb.h = 35,
  mar = c(0, 0, 0, 0),
  cex.text = 2,
  ...
) {
  center <- coo_centpos(original) # center position
  original_centered <- sweep(original, 2, center, "-") # center the contour

  ef <- efourier(
    original_centered,
    nb.h = nb.h,
    norm = FALSE
  )
  true_ef <- true_normalize(ef, output_meta = TRUE)
  true_ef_coef <- true_ef$ef
  true_ef_coef <- list(
    ao = unique(true_ef_coef$ao),
    co = unique(true_ef_coef$co),
    an = true_ef_coef$an,
    bn = true_ef_coef$bn,
    cn = true_ef_coef$cn,
    dn = true_ef_coef$dn
  )
  # reonstruct contour from true EFD coefficients
  reconstruct <- efourier_i(true_ef_coef, nb.h = nb.h)
  df_reconstruct <- as.data.frame(reconstruct)
  df_reconstruct <- df_reconstruct * true_ef$E

  xlim <- range(c(df_reconstruct$x, original_centered[, 1]))

  par(mar = mar)
  # original centered contour
  plot(
    original_centered,
    type = "l",
    asp = 1,
    col = adjustcolor("black", red = 0.7, green = 0.7, blue = 0.7),
    xlim = xlim,
    bty = "n",
    xaxt = "n",
    yaxt = "n",
    xlab = "",
    ylab = "",
    ...
  )

  # reconstructed contour
  lines(
    df_reconstruct,
    asp = 1,
    col = adjustcolor("#FF4B00", alpha.f = 0.9),
    ...
  )
  if (!is.null(label)) {
    text(
      x = mean(par("usr")[1:2]),
      y = mean(par("usr")[3:4]),
      labels = label,
      cex = cex.text,
      col = "black"
    )
  }
}
```

### 保存

```{r}
# ratation
set.seed(123) # set.seed for reproducibility
angles <- sample(0:360, length(xy_list), replace = TRUE) # rotation angles in degrees
# rotate contours
xy_list_rotated <- mapply(
  function(mat, ang) rotate_xy_centered(mat, ang),
  xy_list,
  angles,
  SIMPLIFY = FALSE
)

save_dir <- "results"
dir.create(save_dir, recursive = TRUE, showWarnings = FALSE)
save_path <- file.path(
  save_dir,
  "contour_rotation_reconstrucsion_triadica_sebifera.svg"
)
svg(save_path, width = 10, height = 5, bg = "transparent")
layout(matrix(seq_along(xy_list_rotated), nrow = 5, byrow = TRUE))
for (i in seq_along(xy_list_rotated)) {
  compare_contour(
    original = xy_list_rotated[[i]],
    nb.h = 5,
    mar = c(0, 0, 0, 0),
    lwd = 2,
    cex.text = 1,
    label = names(xy_list_rotated)[i]
  )
}
dev.off()
```

## 一部を保存

```{r}
save_dir <- "results"
dir.create(save_dir, showWarnings = FALSE)
save_file_name <- "compare_contours_true_efd_normalized_triadica_sebifera_example.svg"
svg(file.path(save_dir, save_file_name), bg = "transparent")

xy_list_rotated_example <- xy_list_rotated[1:9]
labels <- letters[seq_along(xy_list_rotated_example)]
layout(matrix(seq_along(xy_list_rotated_example), nrow = 3, byrow = TRUE))
for (i in seq_along(xy_list_rotated_example)) {
  compare_contour(
    original = xy_list_rotated_example[[i]],
    nb.h = 5,
    mar = c(0, 0, 0, 0),
    lwd = 3,
    cex.text = 5,
    label = labels[i]
  )
}
dev.off()
```
