
## ライブラリの読み込み

```{r}
#| label: setup
library(tools)
library(Momocs)
source("documents/functions.R")
palette("Okabe-Ito")
```

種名

```{r}
#| label: species_name
df_sp_name <- read.csv("data/species_name.csv")
df_sp_name$species <- ifelse(
  df_sp_name$konara < df_sp_name$mizunara,
  "mizunara",
  "konara"
)
```

## ランドマークデータ

基部と先端の座標データを読み込みます。

```{r}
#| label: landmark_data

file_paths_meta <- list.files(
  "output/metadata/",
  full.names = TRUE,
  pattern = "\\.csv$"
)
df_meta_list <- lapply(file_paths_meta, read.csv) # make a list of data frames
df_meta <- do.call(rbind, df_meta_list) # combine data frames into one
df_meta <- df_meta[, c("id", "leaf_id", "base_x", "base_y", "tip_x", "tip_y")]
names(df_meta) <- c("id", "leaf_id", "base_y", "base_x", "tip_y", "tip_x") # xy反対だった

df_meta$label <- paste0(
  df_meta$id,
  "_",
  sprintf("%02d", df_meta$leaf_id)
)
```

## 輪郭データ

```{r}
#| label: load_contours
file_paths_xy <- list.files(
  "output/contour/",
  full.names = TRUE,
  pattern = "\\.csv$"
)
id_name <- file_path_sans_ext(basename(file_paths_xy))

id_name_head <- lapply(id_name, function(x) {
  parts <- unlist(strsplit(x, "_"))
  return(parts[1])
})
id_name_head <- unlist(id_name_head)
# 種名の対応付け
sp_name <- df_sp_name$species[match(id_name_head, df_sp_name$id)]

xy_list <- lapply(file_paths_xy, function(fp) {
  cat("File:", fp, "\n")
  df <- read.csv(fp)
  df <- df[, c("x", "y")]
  df <- as.matrix(df)
  storage.mode(df) <- "double"
  # 輪郭が閉じていない場合、最初の点を最後に追加して閉じる
  if (!all(df[1, ] == df[nrow(df), ])) {
    df <- rbind(df, df[1, ])
  }
  return(df)
})
names(xy_list) <- id_name
length(xy_list)
out <- Out(xy_list, fac = data.frame(species = factor(sp_name))) # MomocsのOutオブジェクトに変換
names(out) <- id_name
```

確認

```{r}
stack(out) # 全部重ねる
plot(out$coo$S0186_01, type = "l", asp = 1)
# 基部と先端のプロット
points(
  df_meta$base_x[1],
  df_meta$base_y[1],
  col = 2, # orange
  pch = 19,
  cex = 3
)
points(
  df_meta$tip_x[1],
  df_meta$tip_y[1],
  col = 4, # green
  pch = 19,
  cex = 3
)
```


## 回転関数の作成

```{r}
#| label: rotate_contours

set.seed(123) # set.seed for reproducibility
angles <- sample(0:360, length(out$coo), replace = TRUE) # rotation angles in degrees

# rotate contours
out_rotated <- mapply(
  function(mat, ang) rotate_xy_centered(mat, ang),
  out$coo,
  angles,
  SIMPLIFY = FALSE
)
out_rotated <- Out(out_rotated, fac = out$fac)
#stack(out_rotated)

# 基部と先端のプロットも回転
df_base <- data.frame(
  x = df_meta$base_x,
  y = df_meta$base_y
)
df_tip <- data.frame(
  x = df_meta$tip_x,
  y = df_meta$tip_y
)
cog <- lapply(out$coo, function(mat) {
  c(mean(mat[, 1]), mean(mat[, 2]))
})
df_base_rotated <- rotate_xy_custom_origin(df_base, angles, cog)
df_tip_rotated <- rotate_xy_custom_origin(df_tip, angles, cog)

for (i in 1:5) {
  plot(out$coo[[i]], type = "l", asp = 1)
  # 元の基部と先端
  points(
    df_base$x[i],
    df_base$y[i],
    col = 2,
    pch = 15,
    cex = 3
  )
  points(
    df_tip$x[i],
    df_tip$y[i],
    col = 4,
    pch = 15,
    cex = 3
  )
  lines(out_rotated$coo[[i]], col = 7)
  points(
    df_base_rotated$x[i],
    df_base_rotated$y[i],
    col = 2,
    pch = 19,
    cex = 3
  )
  points(
    df_tip_rotated$x[i],
    df_tip_rotated$y[i],
    col = 4,
    pch = 19,
    cex = 3
  )
}
plot(out_rotated$coo[[1]], type = "l", asp = 1)
```

## EFDの計算

回転後の輪郭座標からEFDを計算します。

```{r}
#| label: efd_rotation_contours

ef_rotated_true_norm <- efourier_true_norm(
  out_rotated,
  nb_h = nb_h,
  x_sy = TRUE,
  y_sy = TRUE
)
pca_rotated <- PCA(ef_rotated_true_norm, center = TRUE, scale. = FALSE)
```

## PCAプロットの作成

```{r}
svg(
  "assets/pca_momocs_efd_normalized_rotation.svg",
  bg = "transparent",
  width = 6,
  height = 6
)
pca_plot <- function(x, ...) {
  plt <- plot_PCA(
    x,
    f = ~species,
    palette = my_palette,
    points = FALSE,
    morphospace = FALSE,
    morphospace_position = "range",
    chull = TRUE, # convex hull
    #chullfilled = TRUE,
    zoom = 1,
    eigen = FALSE,
    box = FALSE,
    ...
  )
  plt <- layer_axes(plt, col = "black", lwd = 1)
  plt <- layer_points(plt, pch = 19, cex = 1, transp = 0.5)
  plt <- layer_morphospace_PCA(plt, size = 1, col = "black")
}
pca_plot(pca_rotated)
dev.off()
```

## 輪郭の再構築

```{r}
#| label: reconstruct_rotated_contours

coe <- ef_rotated_true_norm$coe # coefficients
nb_h <- sum(grepl("^A", colnames(coe))) # number of harmonics
dimnames(ef_rotated_true_norm$coe)[[2]]
coef_list <- lapply(c("A", "B", "C", "D"), function(prefix) {
  coe[, paste0(prefix, 1:nb.h)]
})
names(coef_list) <- c("A", "B", "C", "D")

reconst_list <- lapply(seq_len(dim(coef_list$A)[1]), function(row) {
  cat("ID:", dimnames(coef_list$A)[[1]][row], "\n")
  an <- coef_list$A[row, ]
  bn <- coef_list$B[row, ]
  cn <- coef_list$C[row, ]
  dn <- coef_list$D[row, ]

  # reconstruct shape
  reconstructed_shape <- efourier_shape(
    an,
    bn,
    cn,
    dn,
    nb.h = nb_h,
    nb.pts = 120,
    plot = FALSE
  )
  return(reconstructed_shape)
})

out_reconstructed <- Out(
  reconst_list,
  fac = data.frame(species = factor(sp_name))
) # MomocsのOutオブジェクトに変換
names(out_reconstructed) <- id_name

save_dir <- "assets/reconstructed_contours/"
dir.create(save_dir, recursive = TRUE, showWarnings = FALSE)
idx <- list(
  1:50,
  51:100,
  101:150,
  151:200,
  201:250,
  251:300,
  301:350,
  351:400,
  401:450,
  451:500,
  501:550,
  551:600,
  601:650,
  651:700,
  701:746
)

for (i in seq_along(idx)) {
  slice_i <- slice(out_reconstructed, idx[[i]])
  svg_filename <- paste0(
    save_dir,
    "reconstructed_contours_",
    min(idx[[i]]),
    "_",
    max(idx[[i]]),
    ".svg"
  )
  #svg(svg_filename, width = 10, height = 5, bg = "transparent")
  panel(
    slice_i,
    dim = c(5, 10),
    names = TRUE,
    borders = adjustcolor(2, alpha.f = 0.7)
  )
  #dev.off()
}
```

## 回転後の輪郭と再構築輪郭の比較

```{r}
save_dir <- "assets/contours_rotated/"
dir.create(save_dir, recursive = TRUE, showWarnings = FALSE)
idx <- list(
  1:50,
  51:100,
  101:150,
  151:200,
  201:250,
  251:300,
  301:350,
  351:400,
  401:450,
  451:500,
  501:550,
  551:600,
  601:650,
  651:700,
  701:746
)

for (i in seq_along(idx)) {
  slice_i <- slice(out_rotated, idx[[i]])
  slice_i_reconstructed <- slice(out_reconstructed, idx[[i]])
  svg_filename <- paste0(
    save_dir,
    "contours_",
    min(idx[[i]]),
    "_",
    max(idx[[i]]),
    ".svg"
  )
  svg(svg_filename, width = 10, height = 5, bg = "transparent")
  panel(slice_i, dim = c(5, 10), names = TRUE)
  par(new = TRUE)
  panel(
    slice_i_reconstructed,
    dim = c(5, 10),
    names = TRUE,
    borders = adjustcolor(2, alpha.f = 0.7)
  )
  dev.off()
}
```

## ランドマーク点との対応

### ランドマークの回転

True EFD normalization のパラメータを使用して、ランドマークを回転します。

```{r}
#| label: rotate_landmarks

n <- 4

ef <- efourier(out_rotated[n], nb.h = 35, norm = FALSE) # check
plot(efourier_i(ef), type = "l", asp = 1)

nb_h <- sum(grepl("^A", colnames(ef$coe))) # number of harmonics

ef_true_norm_rotated <- true_normalize(ef, output_meta = TRUE)
```

landmark は (x,y)の順に与えられるデータフレームとします。

```{r}
landmark_transform <- function(landmark, ef_true_norm_rotated) {
  # scalling
  lm <- landmark / ef_true_norm_rotated$E
  # rotation
  psi <- ef_true_norm_rotated$psi
  theta_t <- ef_true_norm_rotated$theta_t
  R_l <- matrix(c(cos(psi), sin(psi), -sin(psi), cos(psi)), 2, byrow = TRUE)
  R_r <- matrix(
    c(
      cos(theta_t),
      -sin(theta_t),
      sin(theta_t),
      cos(theta_t)
    ),
    2,
    byrow = TRUE
  )
  lm_rotated <- R_l %*% R_r %*% t(as.matrix(lm))
  lm_rotated <- t(lm_rotated) # (1,2)
  if (ef_true_norm_rotated$y_sy) {
    lm_rotated[1, 1] <- -lm_rotated[1, 1]
  }
  if (ef_true_norm_rotated$x_sy) {
    lm_rotated[1, 2] <- -lm_rotated[1, 2]
  }
  return(lm_rotated)
}

# 回転後のランドマーク点の変換
base_transformed <- landmark_transform(
  df_base_rotated[n, c("x", "y")],
  ef_true_norm_rotated
)
tip_transformed <- landmark_transform(
  df_tip_rotated[n, c("x", "y")],
  ef_true_norm_rotated
)
```

回転後の輪郭とランドマーク

```{r}
df_base_rotated <- rotate_xy_custom_origin(df_base, angles, cog)
df_tip_rotated <- rotate_xy_custom_origin(df_tip, angles, cog)
plot(out_rotated$coo[[n]], type = "l", asp = 1)

points(
  df_base_rotated$x[n],
  df_base_rotated$y[n],
  col = 2,
  pch = 19,
  cex = 3
)
points(
  df_tip_rotated$x[n],
  df_tip_rotated$y[n],
  col = 4,
  pch = 19,
  cex = 3
)
```

回転後の輪郭をTrue EFD normalizationした後とランドマーク


```{r}
nb_h = 35
contour_reconstructed <- efourier_i(ef_true_norm_rotated$ef, nb.pts = 120)
plot(contour_reconstructed, type = "l", asp = 1) # reconstructed contour


par(new = TRUE)
plot(out_rotated$coo[[n]], type = "l", asp = 1, col = 7) # rotated contour
points(
  df_base_rotated$x[n],
  df_base_rotated$y[n],
  col = 2,
  pch = 19,
  cex = 3
)
points(
  df_tip_rotated$x[n],
  df_tip_rotated$y[n],
  col = 4,
  pch = 19,
  cex = 3
)
# 第1楕円
#first_ecllipse <- efourier_i(ef_true_norm_rotated$ef, nb.h = 1)
#lines(first_ecllipse, col = 6)

```


```{r}
xlim = range(c(base_transformed[1, 1], tip_transformed[1, 1]))
ylim = range(c(base_transformed[1, 2], tip_transformed[1, 2]))
plot(
  base_transformed[1, 1],
  base_transformed[1, 2],
  col = 2,
  pch = 19,
  cex = 3,
  xlim = xlim,
  ylim = ylim,
  asp = 1
)
points(
  tip_transformed[1, 1],
  tip_transformed[1, 2],
  col = 4,
  pch = 19,
  cex = 3
)
lines(contour_reconstructed)
```
